/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "E:\\笔记\\my-notes-vuepress\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-45331222",
    path: "/fontend/vue/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-45331222").then(next)
    },
  },
  {
    path: "/fontend/vue/index.html",
    redirect: "/fontend/vue/"
  },
  {
    name: "v-06a1430f",
    path: "/intro/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-06a1430f").then(next)
    },
  },
  {
    path: "/intro/index.html",
    redirect: "/intro/"
  },
  {
    name: "v-58b8aa4f",
    path: "/scala/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-58b8aa4f").then(next)
    },
  },
  {
    path: "/scala/index.html",
    redirect: "/scala/"
  },
  {
    name: "v-020a9585",
    path: "/hadoop/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-020a9585").then(next)
    },
  },
  {
    path: "/hadoop/index.html",
    redirect: "/hadoop/"
  },
  {
    name: "v-3fe9163c",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3fe9163c").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-7a5d1e78",
    path: "/scala/scala%E5%9F%BA%E7%A1%80.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7a5d1e78").then(next)
    },
  },
  {
    path: "/scala/scala基础.html",
    redirect: "/scala/scala%E5%9F%BA%E7%A1%80.html"
  },
  {
    path: "/scala/scala基础.html",
    redirect: "/scala/scala%E5%9F%BA%E7%A1%80.html"
  },
  {
    name: "v-e09082f0",
    path: "/scala/scala%E9%9B%86%E5%90%88.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e09082f0").then(next)
    },
  },
  {
    path: "/scala/scala集合.html",
    redirect: "/scala/scala%E9%9B%86%E5%90%88.html"
  },
  {
    path: "/scala/scala集合.html",
    redirect: "/scala/scala%E9%9B%86%E5%90%88.html"
  },
  {
    name: "v-429461a2",
    path: "/spark/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-429461a2").then(next)
    },
  },
  {
    path: "/spark/index.html",
    redirect: "/spark/"
  },
  {
    name: "v-7adadf10",
    path: "/spark/Spark%E6%A0%B8%E5%BF%83%E7%BC%96%E7%A8%8B.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7adadf10").then(next)
    },
  },
  {
    path: "/spark/Spark核心编程.html",
    redirect: "/spark/Spark%E6%A0%B8%E5%BF%83%E7%BC%96%E7%A8%8B.html"
  },
  {
    path: "/spark/Spark核心编程.html",
    redirect: "/spark/Spark%E6%A0%B8%E5%BF%83%E7%BC%96%E7%A8%8B.html"
  },
  {
    name: "v-15a156e2",
    path: "/spark/spark%E7%9A%84%E8%BF%90%E8%A1%8C%E6%9E%B6%E6%9E%84.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-15a156e2").then(next)
    },
  },
  {
    path: "/spark/spark的运行架构.html",
    redirect: "/spark/spark%E7%9A%84%E8%BF%90%E8%A1%8C%E6%9E%B6%E6%9E%84.html"
  },
  {
    path: "/spark/spark的运行架构.html",
    redirect: "/spark/spark%E7%9A%84%E8%BF%90%E8%A1%8C%E6%9E%B6%E6%9E%84.html"
  },
  {
    name: "v-02e1c0ed",
    path: "/scala/scala%E6%96%B9%E6%B3%95%E4%B8%8E%E5%87%BD%E6%95%B0.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-02e1c0ed").then(next)
    },
  },
  {
    path: "/scala/scala方法与函数.html",
    redirect: "/scala/scala%E6%96%B9%E6%B3%95%E4%B8%8E%E5%87%BD%E6%95%B0.html"
  },
  {
    path: "/scala/scala方法与函数.html",
    redirect: "/scala/scala%E6%96%B9%E6%B3%95%E4%B8%8E%E5%87%BD%E6%95%B0.html"
  },
  {
    name: "v-0aea1c65",
    path: "/scala/scala%E5%AD%97%E7%AC%A6%E4%B8%B2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0aea1c65").then(next)
    },
  },
  {
    path: "/scala/scala字符串.html",
    redirect: "/scala/scala%E5%AD%97%E7%AC%A6%E4%B8%B2.html"
  },
  {
    path: "/scala/scala字符串.html",
    redirect: "/scala/scala%E5%AD%97%E7%AC%A6%E4%B8%B2.html"
  },
  {
    name: "v-75456660",
    path: "/hadoop/hdfs.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-75456660").then(next)
    },
  },
  {
    path: '*',
    component: GlobalLayout
  }
]