/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "meicilly的学习笔记",
  "description": "meicilly的学习笔记",
  "base": "/",
  "headTags": [],
  "pages": [
    {
      "title": "vue",
      "frontmatter": {},
      "regularPath": "/fontend/vue/",
      "relativePath": "fontend/vue/index.md",
      "key": "v-45331222",
      "path": "/fontend/vue/",
      "headers": [
        {
          "level": 3,
          "title": "vue",
          "slug": "vue"
        }
      ]
    },
    {
      "title": "学习",
      "frontmatter": {},
      "regularPath": "/intro/",
      "relativePath": "intro/index.md",
      "key": "v-06a1430f",
      "path": "/intro/"
    },
    {
      "title": "scala的学习笔记",
      "frontmatter": {},
      "regularPath": "/scala/",
      "relativePath": "scala/index.md",
      "key": "v-58b8aa4f",
      "path": "/scala/",
      "headers": [
        {
          "level": 3,
          "title": "scala的学习笔记",
          "slug": "scala的学习笔记"
        }
      ]
    },
    {
      "title": "1.1HDFS的学习",
      "frontmatter": {},
      "regularPath": "/hadoop/",
      "relativePath": "hadoop/index.md",
      "key": "v-020a9585",
      "path": "/hadoop/",
      "headers": [
        {
          "level": 3,
          "title": "1.1HDFS的学习",
          "slug": "_1-1hdfs的学习"
        },
        {
          "level": 3,
          "title": "H",
          "slug": "h"
        }
      ]
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroText": "meicilly的学习笔记",
        "tagline": "个人笔记",
        "actionText": "get starting →",
        "actionLink": "/scala/",
        "features": [
          {
            "title": "大数据部分",
            "details": "主要整理自己大数据的学习笔记,hadoop,zookeeeper,hive,hbase,spark,fink等组件"
          },
          {
            "title": "java后端部分",
            "details": "整理自己在java后端学习的笔记，例如Mybatis,Spring Boot,Spring Cloud这些组件的使用"
          },
          {
            "title": "前端部分",
            "details": "整理自己js高级部分的学习笔记，例如:promise,防抖节流和响应式的原理，会有vue框架和react框架的实战项目"
          }
        ],
        "footer": "MIT Licensed | Copyright © 2022-present Evan You"
      },
      "regularPath": "/",
      "relativePath": "index.md",
      "key": "v-3fe9163c",
      "path": "/"
    },
    {
      "frontmatter": {},
      "regularPath": "/scala/scala%E5%9F%BA%E7%A1%80.html",
      "relativePath": "scala/scala基础.md",
      "key": "v-7a5d1e78",
      "path": "/scala/scala%E5%9F%BA%E7%A1%80.html",
      "headers": [
        {
          "level": 3,
          "title": "",
          "slug": "_1-1-scala的基础"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/scala/scala%E9%9B%86%E5%90%88.html",
      "relativePath": "scala/scala集合.md",
      "key": "v-e09082f0",
      "path": "/scala/scala%E9%9B%86%E5%90%88.html",
      "headers": [
        {
          "level": 3,
          "title": "",
          "slug": "_4-1-集合"
        }
      ]
    },
    {
      "title": "spark学习",
      "frontmatter": {},
      "regularPath": "/spark/",
      "relativePath": "spark/index.md",
      "key": "v-429461a2",
      "path": "/spark/",
      "headers": [
        {
          "level": 3,
          "title": "spark学习",
          "slug": "spark学习"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/spark/Spark%E6%A0%B8%E5%BF%83%E7%BC%96%E7%A8%8B.html",
      "relativePath": "spark/Spark核心编程.md",
      "key": "v-7adadf10",
      "path": "/spark/Spark%E6%A0%B8%E5%BF%83%E7%BC%96%E7%A8%8B.html",
      "headers": [
        {
          "level": 3,
          "title": "",
          "slug": "_1-1-rdd核心编程"
        },
        {
          "level": 3,
          "title": "",
          "slug": "_1-2rdd的创建"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/spark/spark%E7%9A%84%E8%BF%90%E8%A1%8C%E6%9E%B6%E6%9E%84.html",
      "relativePath": "spark/spark的运行架构.md",
      "key": "v-15a156e2",
      "path": "/spark/spark%E7%9A%84%E8%BF%90%E8%A1%8C%E6%9E%B6%E6%9E%84.html",
      "headers": [
        {
          "level": 3,
          "title": "",
          "slug": "_1-1-spark的运行架构"
        },
        {
          "level": 3,
          "title": "1.2 spark的核心组件",
          "slug": "_1-2-spark的核心组件"
        },
        {
          "level": 3,
          "title": "1.3 核心概念",
          "slug": "_1-3-核心概念"
        },
        {
          "level": 3,
          "title": "1.4 提交流程图",
          "slug": "_1-4-提交流程图"
        }
      ]
    },
    {
      "title": "2.1 scala的方法与函数",
      "frontmatter": {},
      "regularPath": "/scala/scala%E6%96%B9%E6%B3%95%E4%B8%8E%E5%87%BD%E6%95%B0.html",
      "relativePath": "scala/scala方法与函数.md",
      "key": "v-02e1c0ed",
      "path": "/scala/scala%E6%96%B9%E6%B3%95%E4%B8%8E%E5%87%BD%E6%95%B0.html",
      "headers": [
        {
          "level": 3,
          "title": "2.1 scala的方法与函数",
          "slug": "_2-1-scala的方法与函数"
        }
      ]
    },
    {
      "title": "3.1 scala字符串",
      "frontmatter": {},
      "regularPath": "/scala/scala%E5%AD%97%E7%AC%A6%E4%B8%B2.html",
      "relativePath": "scala/scala字符串.md",
      "key": "v-0aea1c65",
      "path": "/scala/scala%E5%AD%97%E7%AC%A6%E4%B8%B2.html",
      "headers": [
        {
          "level": 3,
          "title": "3.1 scala字符串",
          "slug": "_3-1-scala字符串"
        }
      ]
    },
    {
      "title": "1.1HDFS的学习",
      "frontmatter": {},
      "regularPath": "/hadoop/hdfs.html",
      "relativePath": "hadoop/hdfs.md",
      "key": "v-75456660",
      "path": "/hadoop/hdfs.html",
      "headers": [
        {
          "level": 3,
          "title": "1.1HDFS的学习",
          "slug": "_1-1hdfs的学习"
        }
      ]
    }
  ],
  "themeConfig": {
    "displayAllHeaders": true,
    "nav": [
      {
        "text": "主页",
        "link": "/"
      },
      {
        "text": "大数据",
        "items": [
          {
            "text": "hadoop",
            "link": "/hadoop/"
          },
          {
            "text": "scala",
            "link": "/scala/"
          },
          {
            "text": "spark",
            "link": "/spark/"
          }
        ]
      },
      {
        "text": "java后端",
        "link": "/intro/"
      },
      {
        "text": "前端部分",
        "link": "/frontend/index/"
      }
    ],
    "sidebar": {
      "/hadoop/": [
        {
          "title": "hadoop的学习笔记",
          "path": "/hadoop/",
          "collapsable": true,
          "sidebarDepth": 3,
          "children": [
            {
              "title": "1.1 HDFS的学习",
              "path": "/hadoop/hdfs"
            }
          ]
        }
      ],
      "/scala/": [
        {
          "title": "scala的学习笔记",
          "path": "/scala/",
          "collapsable": true,
          "sidebarDepth": 2,
          "children": [
            {
              "title": "1.1 scala的基础学习",
              "path": "/scala/scala基础"
            },
            {
              "title": "1.2 scala方法与函数",
              "path": "/scala/scala方法与函数"
            },
            {
              "title": "1.3 scala字符串",
              "path": "/scala/scala字符串"
            },
            {
              "title": "1.4 scala集合",
              "path": "/scala/scala集合"
            }
          ]
        }
      ],
      "/spark/": [
        {
          "title": "spark的学习笔记",
          "path": "/spark/",
          "collapsable": false,
          "sidebarDepth": 2,
          "children": [
            {
              "title": "1.1 spark的运行架构",
              "path": "/spark/spark的运行架构"
            },
            {
              "title": "1.2 RDD核心编程",
              "path": "/spark/Spark核心编程"
            }
          ]
        }
      ]
    },
    "searchMaxSuggestions": 10
  }
}